// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnriJA1bIGza6LYAKxVlymZPO4IQphuqE',
    appId: '1:904687523024:web:c46e71d257b27edb153ad5',
    messagingSenderId: '904687523024',
    projectId: 'gokantin-c4858',
    authDomain: 'gokantin-c4858.firebaseapp.com',
    storageBucket: 'gokantin-c4858.firebasestorage.app',
    measurementId: 'G-721GJK4FWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfc-ugk5qDUze4K5biWPZYArHhvmpHOBY',
    appId: '1:904687523024:android:7a3d8a79915cd491153ad5',
    messagingSenderId: '904687523024',
    projectId: 'gokantin-c4858',
    storageBucket: 'gokantin-c4858.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa9Q10cPyOtwaZygKgfX7qiTu3c1tJI1Y',
    appId: '1:904687523024:ios:313bdfa81e03be99153ad5',
    messagingSenderId: '904687523024',
    projectId: 'gokantin-c4858',
    storageBucket: 'gokantin-c4858.firebasestorage.app',
    iosBundleId: 'com.example.goKantin',
  );
}
